### ISSUE TITLE
Asignación modulo 1.3

### ISSUE THREAD

**Issue by noesoga** [SistemasTecTlaxiaco/CursoGitHubNoe1#3]
![355586483-e55c03b2-cf80-4635-9612-f8cd8c2bf30a](https://github.com/user-attachments/assets/e00cb48e-2ca3-4c10-a7c7-c060636b009e)
![355586347-48820920-a676-403e-9e44-2f2dac54a9a1 (1)](https://github.com/user-attachments/assets/85a3d6ad-0d44-4e65-a042-882247f3a006)

**Comment by josealfredo79** [comment]
Bien hecho y revisada la tarea 1.3 del Modulo 1
