### ISSUE TITLE
Tarea módulo 2.1

### ISSUE THREAD

**Issue by noesoga** [SistemasTecTlaxiaco/CursoGitHubNoe1#5]
![IMG-20240806-WA0017](https://github.com/user-attachments/assets/fddb95db-9e67-4248-8972-bc832d9322d0)
![IMG-20240806-WA0016](https://github.com/user-attachments/assets/1fbb1e20-8cc0-4337-9e74-9a81e5d5ddea)

**Comment by josealfredo79** [comment]
Bien hecho y revisada la tarea 2.1 del Modulo 2
